# Generated by Django 2.1 on 2019-12-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(1, '全国/多省/多市'), (2, '单省/单市'), (3, '项目')], null=True, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
