# Generated by Django 2.1 on 2019-12-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_app', '0004_auto_20191226_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elevators',
            field=models.TextField(blank=True, null=True, verbose_name='管理梯号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='注册邮箱'),
        ),
    ]
