# Generated by Django 2.0.13 on 2020-02-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_app', '0008_auto_20191227_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
    ]
